if(MOCK_SOURCES)
    add_executable(tc_01_ReceiveSingleShot ${CMAKE_CURRENT_SOURCE_DIR}/mock/tc_01_ReceiveSingleShot/main.cpp)
    target_link_libraries(tc_01_ReceiveSingleShot PRIVATE MercuryCAN)
    target_include_directories(tc_01_ReceiveSingleShot PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
    add_test(NAME tc_01_ReceiveSingleShot COMMAND tc_01_ReceiveSingleShot)
    set_tests_properties(tc_01_ReceiveSingleShot PROPERTIES TIMEOUT 5)

    add_executable(tc_02_TransmitSingleShot ${CMAKE_CURRENT_SOURCE_DIR}/mock/tc_02_TransmitSingleShot/main.cpp)
    target_link_libraries(tc_02_TransmitSingleShot PRIVATE MercuryCAN)
    target_include_directories(tc_02_TransmitSingleShot PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
    add_test(NAME tc_02_TransmitSingleShot COMMAND tc_02_TransmitSingleShot)
    set_tests_properties(tc_02_TransmitSingleShot PROPERTIES TIMEOUT 5)
    
    add_executable(tc_03_ReceiveCyclic ${CMAKE_CURRENT_SOURCE_DIR}/mock/tc_03_ReceiveCyclic/main.cpp)
    target_link_libraries(tc_03_ReceiveCyclic PRIVATE MercuryCAN)
    target_include_directories(tc_03_ReceiveCyclic PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
    add_test(NAME tc_03_ReceiveCyclic COMMAND tc_03_ReceiveCyclic)
    set_tests_properties(tc_03_ReceiveCyclic PROPERTIES TIMEOUT 5)
    
    add_executable(tc_04_TransmitCyclic ${CMAKE_CURRENT_SOURCE_DIR}/mock/tc_04_TransmitCyclic/main.cpp)
    target_link_libraries(tc_04_TransmitCyclic PRIVATE MercuryCAN)
    target_include_directories(tc_04_TransmitCyclic PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
    add_test(NAME tc_04_TransmitCyclic COMMAND tc_04_TransmitCyclic)
    set_tests_properties(tc_04_TransmitCyclic PROPERTIES TIMEOUT 5)
endif()