set(CMAKE_C_STANDARD 23)
set(CMAKE_CXX_STANDARD 23)

set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)

set(MCU at90can128 CACHE STRING "AVR MCU")
set(FRQ 16000000UL CACHE STRING "AVR CPU frequency")

set(CMAKE_C_FLAGS
    "-D__AVR_AT90CAN128__ -DF_CPU=${FRQ} -Ofast -Wall -D__USE_MOCK_DRIVER"
    CACHE STRING "AVR compiler flags"
)

set(CMAKE_CXX_FLAGS
    "-D__AVR_AT90CAN128__ -DF_CPU=${FRQ} -Ofast -Wall -fno-threadsafe-statics -D__USE_MOCK_DRIVER"
    CACHE STRING "AVR compiler flags"
)

set(CMAKE_EXE_LINKER_FLAGS
    "-mmcu=${MCU}"
    CACHE STRING "AVR linker flags"
)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)